#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch=$(git symbolic-ref --short HEAD)

if ! echo "$branch" | grep -qE '^CU-[a-zA-Z0-9-]+$'; then
  echo "Branch name must follow ClickUp format: CU-<id>"
  echo "Example: CU-86ahefu3e"

  exit 1
fi

(cd shared && npx lint-staged && npm run typecheck)
(cd web && npx lint-staged && npm run typecheck)
(cd server && npx lint-staged && npm run typecheck)
